### PR TITLE
Add jingles option to AO

### PR DESCRIPTION
**Pull request by AxelTerizaki**
This is part of Karaoke Mugen's team's efforts to push back some of our changes to AO (and as a thanks for all the bugs fixed)

Jingles are video files in the "jingles" directory.

They are only played if JINGLES_INTERVAL is set and > 0

Jingles can be used to display small, funny spots or ads/promotions

### CODE REVIEW

**Comment by AxelTerizaki** [comment]
Forgot to mention that obviously `JINGLES_INTERVAL` sets how many songs must be played before a jingle is played. Jingles are selected randomly from the jingles directory each time.

**Comment by Yay295** [comment]
So the difference between a Jingle and an Easter Egg is that a Jingle will always be played every `JINGLES_INTERVAL` number of videos?

**Comment by AxelTerizaki** [comment]
Yes, and Jingles cannot be played randomly  as they're not part of the regular playlist.

**Comment by Yay295** [comment]
Some concerns I have:
1. This code is specific to mp4 files. If you use webm instead of mp4, `glob("../jingles/*.mp4")` won't work. This is why we added the `mime` entry for each video. It allows you to specify which files to look for. `'mime' => $data['mime']` is also completely wrong because it is taking the `mime` field from the current video rather than from the Jingle video (which doesn't have any metadata in your setup).
2. It adds another video type by working around the limitations of the system rather than expanding the limitations. Easter Eggs are already their own special type, and on openings.moe we determine Opening, Insert, and Ending types based on the file name. Jingles would be a fifth type with their own special way of being defined.

I have an idea for a cleaner solution I'm working on now, but thanks for bringing this up so I have a data set to work with.

**Comment by AxelTerizaki** [comment]
You have very valid points there. I'm sure your solution will be cleaner and we'd love to be able to use it instead. :)

**Comment by Yay295** [comment]
It might be a while until I have time to get everything changed, but basically my idea is to replace the `egg` metadata attribute with a `type` attribute, and have the `$VIDEO_TYPES` be specified in `config.php`. Here's what I currently have for config setting, though I might still change it a bit:

```php
$VIDEO_TYPES = [
    '' => [ // The '' type is the default that will be used if an unknown type is seen.
        'name' => '',
        'abbreviation' => '',
        'src_dir' => 'video',   // The directory videos of this type are stored under.
        'chance' => 0.0,        // The chance that a video of this type will be returned (numbers should be in the range [0,1]).
        'interval' => 0         // If not 0, a video of this type must be shown every "interval" videos on the main page.
    ],
    'JI' => [
        'name' => 'Jingle',
        'abbreviation' => 'JI',
        'src_dir' => 'jingles',
        'chance' => 0.0,
        'interval' => 6
    ]
];
```

**Comment by AxelTerizaki** [comment]
Just to be sure, this is not the same as song type (Opening, Ending, Insert song, etc.)

I think this would need to be clarified so users know what is what exactly :)

Making a difference on interval and chance is a pretty neat idea, I didn't think of that. We used interval because in Karaoke Mugen we usually use these, but a chance percentage could have other uses (like for eggs indeed)

**Comment by Yay295** [comment]
so that took a while, huh?

fixed with commit c3941d19e79aa0fc005642682a1a9d75b18ccfab

**Pull request closed without merging**
