### PR TITLE
MUH BANDWITH

### PR DESCRIPTION
**Pull request by TheHowl**

### CODE REVIEW

**Comment by QuadPiece** [comment]
No. JS is not getting minified or shrined. This wastes resources on the server side and is generally annoying for developers who look at the site.

The JS was originally minified and combines. But it was split for the convenience of my dear devs

**Comment by TheHowl** [comment]
but the sauce is linked on the minified javascript at the top

And muh bandwith x2 ;-;

**Comment by QuadPiece** [comment]
Don't worry.

I pay for MUH BANDWIDTH here, not you

**Comment by TheHowl** [comment]
I wasn't talking about that. I was talking more about the loading speed of the page from people with le shit connection

On 6 April 2015 14:27:49 CEST, "Dominik V. Salonen" <notifications@github.com> wrote:
>Don't worry.
>
>I pay for MUH BANDWIDTH here, not you
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/AniDevTwitter/animeopenings/pull/4#issuecomment-90038777

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by QuadPiece** [comment]
The website loads in about 4 seconds over 50 kbps EDGE.

kek, Do you really think I haven't tested this?

People with shit net won't be able to stream the 3 mbit/s webms properly anyways

**Pull request closed without merging**
