### PR TITLE
Revert "Fixed bug in some browsers where the JS runs before the video…

### PR DESCRIPTION
**Pull request by QuadPiece**
Reverts AniDevTwitter/animeopenings#44

### CODE REVIEW

**Comment by TheHowl** [comment]
hey quad

`git revert f0e4a17`

just saying

**Comment by QuadPiece** [comment]
I'm on Winblows rn and I hate git shell

**Comment by TheHowl** [comment]
install babun

**Comment by QuadPiece** [comment]
I have babun. But the Web UI works.

I mean this took me like 5 seconds.

**Comment by TheHowl** [comment]
not 1337 enough

**Comment by QuadPiece** [comment]
We all know I'm more 1337 than you bby

**Pull request merged**
