### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Yay295**
index.php:
Updated meta theme-color
Removed video count
Moved CSS to CSS/main.css
Removed (commented out) unused code for mobile

CSS/main.css:
Slightly changed colors for consistency
Removed unused styles
Moved styles to their proper places

### CODE REVIEW

**Comment by TheHowl** [comment]
9 days later

**Comment by QuadPiece** [comment]
Yeah. Some people have a life :^)

**Comment by QuadPiece** [comment]
I haven't been on a computer capable of running git in the last 9 days

**Comment by TheHowl** [comment]
not you though

Il 05/09/2015 15:44, Dominik V. Salonen ha scritto:

**Comment by QuadPiece** [comment]
plz, Twitter is a life

**Pull request merged**
