### PR TITLE
Render hub/* statically because it's static

### PR DESCRIPTION
**Pull request by rm-you**
Removing the unused botnet.html includes that are the only thing that actually require PHP. Botnet code can easily be added back by putting the botnet stuff in a botnet.js file and including it via <script> tag.

### CODE REVIEW

**Comment by rm-you** [comment]
So, this is a direction choice -- I recommend it, but it may not be what you want to do. On my fork I've completely removed PHP from the requirements for the project, and it works great. I have a commit nearly ready for the rest of the change.

**Comment by QuadPiece** [comment]
Technically all you did here was move the dynamic processing of the navbar from PHP to JS client-side. And remove the botnet include.

The botnet.html include is there for other users who clone the repo for the most part. We haven't used it in ages. Also due to how our caching works, moving from navbar.php to navbar.js would actually decrease performance. Since currently, hub pages are cached statically.

Not a bad suggestion, but it doesn't fit our use at all. Good luck with your rewrite away from PHP

**Comment by rm-you** [comment]
Right, this is part one of two... It takes care of the Hub only. Part 2 removes the rest of the PHP code, rendering the entire site via JS only. If it's not something you're interested in, I will not continue work on that PR (it sounds like you are not).

**Comment by QuadPiece** [comment]
Not until I see considerable performance improvements.

**Pull request closed without merging**
