### PR TITLE
use more modern js

### PR DESCRIPTION
**Pull request by Yay295**

### CODE REVIEW

**Comment by rm-you** [comment]
So, "let" is great and all I guess? But, it only works with the very newest ECMAScript spec and so a LOT of browsers don't support it properly (or if they do, they throw warnings about requiring "strict mode" and halt processing JS). I've actually had to go through and specifically replace all of the existing "let" with "var" for compatibility, because the performance improvement isn't nearly worth it for the compatibility loss. I highly recommend not merging this.

**Comment by Yay295** [comment]
It seems pretty well supported to me: http://caniuse.com/#search=let

**Comment by rm-you** [comment]
It's getting better, but there are still people on older versions of Chrome (because they can't update due to various reasons -- no admin access, or EOL'd device) and switching to "let" breaks them for no large benefit.

**Comment by QuadPiece** [comment]
Only considerable issue I see here is Mac support. Though it's not like they can play our vids anyways. So I'll merge it. Worst case we can revert.

**Pull request merged**
