### PR TITLE
Audio normalization

### PR DESCRIPTION
**Pull request by KuroPon**
Wrote python script to make encoding easier/less error prone.
It also automatically normalizes volume levels.
Created new directory 'encode'. Moved 'encoding-settings' to 'encode/settings'.
Added new encoding setting (4.2) to reflect increased audio quality (192k),
audio normalization and the script.

### CODE REVIEW

**Comment by plueschopath** [comment]
We shouldn't let the volume reach 0.0 dB. I'm not exactly sure why, but in the cubase youtube mixing/mastering howtos I've watched on youtube, they always mix to something like -0.3 dB iirc.

To fix that go to line 121 and change return dB * -1.0 to return (dB * -1.0) - 0.3

@QuadPiece, can you do that after the merge and maybe share your opinion about it?

**Comment by plueschopath** [comment]
@KuroPon and me tested it out a bit more. We should change line 121 to "return (dB * -1.0) - 1". This gives ffmpeg some headroom that should be save for encoding.

In my test with the modified line 121 the result is a file ffmpeg -af "volumedetect" detects max_volume at -0.5 dB.

The result from @KuroPon is here: http://pastebin.com/En7Nq7Cp

**Comment by KuroPon** [comment]
The inconsistencies seem to be due to floating point rounding errors.
In 0a11636 I set the filter to fixed percision which (should) now guarantee a maximum volume of
-0.5dB for every video.

**Comment by KuroPon** [comment]
Reading documentation instead of testing blindly helps ...
On the ffmpeg page (see https://ffmpeg.org/ffmpeg-filters.html#Examples-18 ) it states:
"The largest sample is at -4 dB, or more precisely between -4 dB and -5 dB."
and "In other words, raising the volume by +4 dB does not cause any clipping" 
So it guarantees no clipping, but different videos will not have 100% identical maximum volume.
Though (in my opinion) very mild fluctuations (less than 1dB) between videos aren't important and barley perceptible anyways.

**Comment by plueschopath** [comment]
We can merge this now.

**Pull request merged**
