### PR TITLE
Update encodes.php

### PR DESCRIPTION
**Pull request by Yay295**

### CODE REVIEW

**Comment by QuadPiece** [comment]
I'm not really sure if this is optimal, since things on file.quad.moe get deleted after one week of inactivity

**Comment by Yay295** [comment]
Hopefully people will stick around then. I can't access 1339.cf though, so that's not really optimal either.

**Comment by QuadPiece** [comment]
Well shucks, can you access mixtape.moe then?

**Comment by Yay295** [comment]
Yes I can.

**Comment by QuadPiece** [comment]
Then let's try using that instead

**Pull request merged**
