### PR TITLE
Hiii

### PR DESCRIPTION
**Pull request by nyanimex**
Hi Friend, nice code, http://openings.moe Help me, I need create one site similar, You have help me ? for create one site... and I can share your openings, your videos

### CODE REVIEW

**Comment by thehowl** [comment]
Have you got the slightest idea of what you're doing?

**Comment by QuadPiece** [comment]
w-why is there an entire duplicate of our repo being pull requested right here? also might i request that you write in English. If you're not that good, use Google Translate, i can at least guess what that wants to say.

**Comment by QuadPiece** [comment]
Also why on earth would you pull into a revert branch

**Comment by thehowl** [comment]
They probably just wanted to create an issue and fucked up.

**Comment by QuadPiece** [comment]
@thehowl I guess, but I don't even know how to do this on purpose. So good job.

**Pull request closed without merging**
