### PR TITLE
show link in url, and loop on direct link

### PR DESCRIPTION
**Pull request by Yay295**
addresses issues #183 and #213

This will make it so that the direct link to the video will always show in the URL (unless it's an Easter Egg), and if a direct link is used to navigate to the page, it will loop that video instead of using whatever was set in LocalStorage.

### CODE REVIEW

**Comment by TazeTSchnitzel** [comment]
\o/

**Comment by TazeTSchnitzel** [comment]
Doesn't this mean that browser history is strictly inaccurate? If you always show the link in the URL even for non-looping, yet navigating to said URL uses looping, then reöpening the same URL (say after closing the browser) will leave you stuck on the same video.

**Comment by Yay295** [comment]
Yes, I just realized that too. I'll add a flag for it when I have time.

**Comment by Yay295** [comment]
fixed in #223

**Pull request merged**
